---

- name: Add td-agent user to the jetty group so it can read logs
  user:
    name: td-agent
    groups: jetty

- name: Add TresureData repositoy
  yum_repository:
    name: TreasureData
    description: Contains the td-agent
    baseurl: http://packages.treasuredata.com/4/redhat/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://packages.treasuredata.com/GPG-KEY-td-agent

- name: Install td-agent
  yum:
    pkg:
      - td-agent
    state: installed

- name: Install Kinesis plugin
  gem:
    executable: /sbin/td-agent-gem
    name: fluent-plugin-kinesis
    status: latest
    user_install: no
