---

- name: FTicks... Add td-agent user to the jetty group so it can read logs
  user:
    name: td-agent
    groups: jetty

- name: FTicks... Add TresureData repositoy
  yum_repository:
    name: TreasureData
    description: Contains the td-agent
    baseurl: http://packages.treasuredata.com/4/redhat/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://packages.treasuredata.com/GPG-KEY-td-agent

- name: FTicks... Install td-agent
  yum:
    pkg:
      - td-agent
    state: installed

- name: FTicks... Install Kinesis plugin
  gem:
    executable: /sbin/td-agent-gem
    name: fluent-plugin-kinesis
    state: latest
    user_install: no

- name: FTicks... Configure td-agent to forward to aggregator
  template:
    src: fticks-forwarder/td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: root
    mode: u=rw,g=r,o=r
  notify: Restart td-agent

- name: FTicks... Enable and starti the td-agent service
  service:
    name: td-agent
    enabled: yes
    state: started
